// src/productData.js

export const products = [
    {
      name: "Golden Studs",
      price: 1200,
      img: "https://via.placeholder.com/300x300?text=Golden+Studs",
      description: "Elegant 18K gold studs with delicate design",
      category: "Studs",
      isNew: true,
      rating: 4.8,
    },
    {
      name: "Diamond Drops",
      price: 2200,
      img: "https://via.placeholder.com/300x300?text=Diamond+Drops",
      description: "Sparkling diamond drops with white gold setting",
      category: "Drops",
      isNew: true,
      rating: 4.9,
    },
    {
      name: "Silver Hoops",
      price: 1800,
      img: "https://via.placeholder.com/300x300?text=Silver+Hoops",
      description: "Sleek silver hoops for everyday elegance",
      category: "Hoops",
      isNew: false,
      rating: 4.5,
    },
    {
      name: "Traditional Jhumkas",
      price: 2500,
      img: "https://via.placeholder.com/300x300?text=Traditional+Jhumkas",
      description: "Classic jhumkas with intricate Indian design",
      category: "Jhumkas",
      isNew: true,
      rating: 4.7,
    },
    {
      name: "Chandelier Charm",
      price: 2700,
      img: "https://via.placeholder.com/300x300?text=Chandelier+Charm",
      description: "Luxurious chandeliers with gemstone accents",
      category: "Chandeliers",
      isNew: false,
      rating: 4.6,
    },
    {
      name: "Pearl Dangles",
      price: 1900,
      img: "https://via.placeholder.com/300x300?text=Pearl+Dangles",
      description: "Timeless pearl dangles for grace and poise",
      category: "Pearls",
      isNew: false,
      rating: 4.4,
    },
    {
      name: "Tassel Twist",
      price: 1500,
      img: "https://via.placeholder.com/300x300?text=Tassel+Twist",
      description: "Trendy tassel earrings with pastel threads",
      category: "Tassels",
      isNew: true,
      rating: 4.3,
    },
    {
      name: "Kundan Royale",
      price: 2900,
      img: "https://via.placeholder.com/300x300?text=Kundan+Royale",
      description: "Royal Kundan earrings with antique gold finish",
      category: "Kundan",
      isNew: false,
      rating: 4.8,
    },
    {
      name: "Minimalist Studs",
      price: 1100,
      img: "https://via.placeholder.com/300x300?text=Minimalist+Studs",
      description: "Sleek minimal studs for modern flair",
      category: "Minimalist",
      isNew: true,
      rating: 4.2,
    },
  ];